[build]
builder = "nixpacks"

[phases.composer]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.application]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.npm]
cmds = [
  "npm install",
  "npm run build"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"
